```{r, echo=FALSE}
library("RPostgreSQL")
library("tidyverse")
library("ggplot2")
```

```{r, echo=FALSE}
dsn_database = "basi24"     # set your db name here
dsn_server = "localhost"    # set the db server here
dsn_port = "5432"           # set the server listening port here
dsn_uid = "postgres"        # set the user id here
dsn_pswd = "postgres"       # set the user password here

tryCatch({                  
    drv <- dbDriver("PostgreSQL")
    print("Connecting to Database...")
    connec <- dbConnect(drv,
                dbname = dsn_database,
                host = dsn_server,
                port = dsn_port,
                user = dsn_uid,
                password = dsn_pswd)
    print("Database Connected!")
},
error = function(cond) {
    print("Unable to connect to Database")
})
```

# 1 # Ottieni il numero di interventi per ogni anno

```{r, echo = FALSE}
interv_dist <- dbGetQuery(connec, "SELECT EXTRACT(year FROM data) as anno, 
                                        count(*) as n_interventi
                                    FROM progetto_basi.intervento 
                                    GROUP BY anno
                                    ORDER BY anno")

interv_dist$legend <- factor(interv_dist$anno, levels = c(2019, 2020, 2021))

ggplot(interv_dist, aes(anno, n_interventi, fill=legend)) + 
    geom_bar(stat="identity") +
    xlab("Tempo") +
    ylab("Interventi") +
    guides(fill="none") +
    theme_bw() +
    theme(text=element_text(size = 12))

ggsave(file=".graphs/interv_years.png", width=3, height=6, dpi=300)
```

# 2 # Ottieni il numero di interventi per ogni mese in ordine cronologico

```{r, echo = FALSE}
intervento_df <- dbGetQuery(connec, "SELECT TO_DATE(TO_CHAR(data, 'yyyy-MM-01'), 'YYYY-MM-DD') AS date, COUNT(*) as numero_interventi 
                                    FROM progetto_basi.intervento
                                    GROUP BY date
                                    ORDER BY date") ;

# palette is a set of 36 colors used to color the 36 dots 
palette <- rep(c("blue", "red", ...), length.out = 36)

Legenda <- as.factor(intervento_df$date)

print(Legenda)

# in order to map values into colors, as.factor(data) is used
ggplot(intervento_df, aes(x = date, y = numero_interventi, color = Legenda, group = 1)) +
    geom_point() +
    scale_fill_manual(values = palette) +
    geom_line() +
    xlab("Tempo") + 
    ylab("Interventi") +
    theme_bw() + 
    theme(text=element_text(size = 17))

ggsave(file=".graphs/interv_months.png", width=15, height=5, dpi=300)
```

# 3 # Ottieni il numero di interventi per tipo di problema

```{r, echo=FALSE}
distfreq_type_interv_df <- dbGetQuery(connec, "SELECT competenza as tipoproblema, COUNT(*) as numero_interventi 
                                                FROM progetto_basi.registrointerventi as r NATURAL JOIN progetto_basi.possiede as p
                                                GROUP BY tipoproblema")

ggplot(distfreq_type_interv_df, aes(tipoproblema, numero_interventi, fill=tipoproblema)) + 
    geom_bar(stat="identity") +
    guides(fill="none") +
    xlab("Tipo di problema") +
    ylab("Interventi") +
    theme_bw() +
    theme(text=element_text(size = 14))

ggsave(file=".graphs/interv_problemtype.png", width=8, height=10, dpi=300)
```

# 4 # Ottieni la distribuzione di frequenza degli interventi effettuati dai singoli tecnici nel 2020

```{r, echo=FALSE}
raw_df <- dbGetQuery(connec, "SELECT t1.tecnico, t1.n_interventi
                            FROM (SELECT tecnico, count(*) as n_interventi
                                FROM progetto_basi.RegistroInterventi as r, progetto_basi.Intervento as i 
                                WHERE r.richiesta = i.richiesta AND r.intervento = i.nintervento AND i.data > '2020-1-1' AND i.data < '2021-1-1'
                                GROUP BY tecnico) t1
                            ORDER BY t1.n_interventi DESC")

distfreq_technician_interv_df <-
    raw_df %>%
    mutate(freq = (n_interventi / sum(raw_df$n_interventi)) * 100) %>%
    mutate(across(where(is.numeric), ~ round(., 3)))

ggplot(distfreq_technician_interv_df, aes(x="", y=n_interventi, fill=tecnico)) +
    geom_bar(stat="identity", width=1) +
    coord_polar("y", start=0) +
    guides(fill=guide_legend(title="Tecnico")) +
    geom_text(aes(label = paste0(freq, "%")), position = position_stack(vjust=0.5), size=6) +
    labs(x = NULL, y = NULL, fill = NULL) +
    theme_void() +
    theme(text=element_text(size = 12))

ggsave(file=".graphs/percent_interv_tech.jpg", width=13, height=10, dpi=300)
```

# 5 # Ottieni il numero di intervento per tipo problema dei 5 clienti con più interventi registrati

```{r, echo=FALSE}
best_client_df <- dbGetQuery(connec, "SELECT cliente, tipoproblema, COUNT(*) as nInterventi 
                                        FROM progetto_basi.registrointerventi JOIN progetto_basi.richiesta on npratica = registrointerventi.richiesta
                                        WHERE cliente in (
                                                    SELECT cliente
                                                    FROM (SELECT cliente, tipoproblema, COUNT(*) as nInterventi 
                                                            FROM progetto_basi.registrointerventi JOIN progetto_basi.richiesta on npratica = registrointerventi.richiesta
                                                            GROUP BY (cliente, tipoproblema)
                                                            ORDER BY nInterventi) t1
                                                    GROUP BY (cliente)
                                                    Order BY (SUM(nInterventi)) DESC
                                                    LIMIT 5)
                                            GROUP BY (cliente,tipoproblema);")


best_client_df$cliente <- as.character(best_client_df$cliente)
array <- paste("cliente", unique(best_client_df$cliente) , sep = "_")

ggplot(best_client_df, aes(fill = tipoproblema, y = ninterventi, x = cliente)) +
    geom_bar(position='stack', stat='identity') +
    theme_bw() + 
    xlab("Clienti") + 
    ylab("Interventi") +
    guides(fill=guide_legend(title="Tipo di problema")) +
    scale_x_discrete(labels = array) +
    theme(text=element_text(size = 14))

ggsave(file=".graphs/top_5_clients.jpg", width=8, height=8, dpi=300)
```

```{r, echo=FALSE}
best_client_df <- dbGetQuery(connec, "SELECT * FROM progetto_basi.Tecnico")

print(best_client_df)
```